### ISSUE TITLE
`get': HTTP error, code 500 (Hackpad::Cli::ApiException)

### ISSUE THREAD

**Issue by thomaswrenn** [mose/hackpad-cli#3]
`> hpcli getnew                                                                                                               rubyenv:system@2.7.6`
`New pads:`
`/Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/api.rb:54:in`get': HTTP error, code 500 (Hackpad::Cli::ApiException)`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/api.rb:38:in `read'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/pad.rb:46:in`load_from_provider'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/pad.rb:37:in `load'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/padlist.rb:40:in`block in get_new'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/padlist.rb:37:in `each'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/padlist.rb:37:in`get_new'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/client.rb:62:in `getnew'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/lib/hackpad/cli/runner.rb:77:in`getnew'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hackpad-cli-0.1.2/bin/hpcli:5:in `<top (required)>'`
`from /Users/thomaswrenn/.rbenv/versions/2.2.2/bin/hpcli:23:in`load'`
`   from /Users/thomaswrenn/.rbenv/versions/2.2.2/bin/hpcli:23:in `<main>'`

**Comment by mose** [comment]
Something may have changed in the hackpad api. I fixed this problem it in version 0.1.3.
